"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import logging
import os
from datetime import timedelta
from pathlib import Path

import dj_database_url

_settings_logger = logging.getLogger(__name__)

# Load environment variables from .env file in development
# We look for .env.local first, then .env in the root directory
try:
    from dotenv import load_dotenv
    
    # root_path is two levels up from settings.py (backend/config/settings.py -> backend/ -> ./)
    root_path = Path(__file__).resolve().parent.parent.parent
    
    # Load .env.local first (local overrides)
    local_env = root_path / ".env.local"
    if local_env.exists():
        load_dotenv(local_env)
        _settings_logger.info(f"Loaded environment from {local_env}")
    
    # Then load .env (base config)
    base_env = root_path / ".env"
    if base_env.exists():
        load_dotenv(base_env)
        _settings_logger.info(f"Loaded environment from {base_env}")
        
except ImportError:
    pass  # python-dotenv not installed, using system env vars

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# SECURITY SETTINGS
# =============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    # Fallback for development only - NEVER use in production
    import warnings

    warnings.warn(
        "DJANGO_SECRET_KEY not set! Using insecure default. "
        "Set DJANGO_SECRET_KEY environment variable for production.",
        RuntimeWarning,
    )
    SECRET_KEY = "django-insecure-dev-only-30k267t3v3vj-CHANGE-IN-PRODUCTION"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "yes")

# Parse ALLOWED_HOSTS from environment
_env_hosts = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1,.myregistra.net").split(",")
ALLOWED_HOSTS = [host.strip() for host in _env_hosts if host.strip()]

# Explicitly add localhost and 127.0.0.1 to handle internal health checks/curls
if "localhost" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("localhost")
if "127.0.0.1" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("127.0.0.1")

# IMPORANT: Include container names for internal Docker communication
# "backend" is the service name, "registra_backend" is the container name
# Next.js calls http://backend:8000, so Django sees "Host: backend:8000"
INTERNAL_HOSTS = ["backend", "registra_backend", "frontend", "registra_frontend", "nginx"]
for h in INTERNAL_HOSTS:
    if h not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(h)

ROOT_DOMAIN = os.environ.get("ROOT_DOMAIN", "myregistra.net")

# AI Service Keys (Centralized)
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY")


# =============================================================================
# PAYMENT GATEWAY CONFIGURATION (Paystack)
# =============================================================================

PAYSTACK_SECRET_KEY = os.environ.get("PAYSTACK_SECRET_KEY", "")
PAYSTACK_PUBLIC_KEY = os.environ.get("PAYSTACK_PUBLIC_KEY", "")
PAYSTACK_REFERENCE_PREFIX = "EDU"
PAYSTACK_WEBHOOK_SECRET = os.environ.get("PAYSTACK_WEBHOOK_SECRET", "")

# Enable test mode if not in production
PAYSTACK_TEST_MODE = DEBUG


# =============================================================================
# SMS/WhatsApp CONFIGURATION (Termii)
# =============================================================================

TERMII_API_KEY = os.environ.get("TERMII_API_KEY", "")
TERMII_SENDER_ID = os.environ.get("TERMII_SENDER_ID", "")
TERMII_CHANNEL = os.environ.get("TERMII_CHANNEL", "dnd")  # dnd, sms, whatsapp


# =============================================================================
# APPLICATION DEFINITION
# =============================================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",  # For token rotation
    "corsheaders",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    # Local
    "core",
    "schools",
    "users",
    "hr",
    "admissions",
    "academic",
    "bursary",
    "learning",
    "lms",
    "emails",
    "library",
    "inventory",
    "data_import",
    "transport",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.security_middleware.SecurityHeadersMiddleware",
    "core.security_middleware.RequestSizeLimitMiddleware",
    "core.security_middleware.IPAccessControlMiddleware",
    "core.middleware.TenantMiddleware",
    "core.middleware.AuditLogMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Documentation/Frontend URLs
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================

# Use DATABASE_URL environment variable if provided, fallback to SQLite
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=int(os.environ.get("DB_CONN_MAX_AGE", 60)),
        conn_health_checks=True,
    ),
    "replica": dj_database_url.config(
        env="REPLICA_DATABASE_URL",
        default=os.environ.get("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=int(os.environ.get("DB_CONN_MAX_AGE", 60)),
        conn_health_checks=True,
    ),

}

DATABASE_ROUTERS = ["config.routers.DbRouter"]


# If using PostgreSQL, ensure it has some default options
if DATABASES["default"].get("ENGINE") == "django.db.backends.postgresql":
    DATABASES["default"]["OPTIONS"] = DATABASES["default"].get("OPTIONS", {})
    DATABASES["default"]["OPTIONS"].update(
        {
            "connect_timeout": 10,
        }
    )

# NOTE: Coolify manages database connections via DATABASE_URL environment variable
# with dynamically generated container hostnames. Do not override DB_HOST.


# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Increase max upload size for base64 images
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# Enforce PostgreSQL in Production — hard failure, not a silent warning.
# A misconfigured DATABASE_URL would otherwise let Django start on SQLite
# with no durability, no concurrency, and data loss on container restart.
if not DEBUG and DATABASES["default"]["ENGINE"] == "django.db.backends.sqlite3":
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "DATABASE_URL must be set in production. SQLite is not supported. "
        "Set DATABASE_URL to a PostgreSQL connection string and redeploy."
    )


# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "core.password_validators.PasswordComplexityValidator",
        "OPTIONS": {
            "min_length": 8,
        },
    },
    {
        "NAME": "core.password_validators.CommonPasswordPatternValidator",
    },
]


# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Africa/Lagos"  # Nigerian timezone
USE_I18N = True
USE_TZ = True


# =============================================================================
# STATIC FILES
# =============================================================================

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")] if os.path.exists(os.path.join(BASE_DIR, "static")) else []


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# =============================================================================
# AUTH CONFIGURATION
# =============================================================================

AUTH_USER_MODEL = "users.User"

AUTHENTICATION_BACKENDS = [
    "users.backends.EmailOrUsernameModelBackend",
    "django.contrib.auth.backends.ModelBackend",
]


# =============================================================================
# REST FRAMEWORK CONFIGURATION
# =============================================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("rest_framework_simplejwt.authentication.JWTAuthentication",),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
        "auth": "5/minute",
        "login_fail": "10/minute",
        "api": "100/minute",
        "burst": "20/minute",
        "sustained": "500/hour",
    },
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Registra API",
    "DESCRIPTION": "Multi-tenant School Management System API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_PATCH": True,
    "COMPONENT_SPLIT_REQUEST": True,
    "SWAGGER_UI_DIST": "SIDECAR",  # optional: include swagger-ui as sidecar
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}


# =============================================================================
# JWT CONFIGURATION
# =============================================================================

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.environ.get("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", 15))),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        hours=int(os.environ.get("JWT_REFRESH_TOKEN_LIFETIME_HOURS", 24))
    ),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_REUSE_DETECTION_ERROR_MESSAGE": "Token has been revoked",
    "TOKEN_REUSE_DETECTION_CLASS": "core.security_utils.RevokedTokenReuseDetection",
}

# =============================================================================
# REDIS CONFIGURATION (for caching and token blacklist)
# =============================================================================

REDIS_URL = os.environ.get("REDIS_URL", os.environ.get("CELERY_BROKER_URL", None))
REDIS_BLACKLIST_TTL = int(os.environ.get("REDIS_BLACKLIST_TTL_SECONDS", 604800))  # 7 days default


# =============================================================================
# CORS CONFIGURATION
# =============================================================================

# Parse CORS origins from environment
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CORS_ALLOWED_ORIGINS", "https://myregistra.net,http://localhost:3000").split(",")
    if origin.strip()
]

# Explicitly add main domains as requested
_main_domains = ["https://myregistra.net", "https://www.myregistra.net"]
for dom in _main_domains:
    if dom not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(dom)

# Use a regex to allow all tenant subdomains (e.g. https://schoolname.myregistra.net)
# This is cleaner than manual wildcard addition and safer
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://[a-zA-Z0-9-]+\.myregistra\.net$",
]

CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ["Content-Type", "X-CSRFToken"]

# CSRF settings for production
CSRF_TRUSTED_ORIGINS = [
    origin.replace("http://", "https://") if origin.startswith("http://") else origin for origin in CORS_ALLOWED_ORIGINS
]

# Explicitly add root and wildcard for subdomains (Critical for Admin POST requests)
_root = os.environ.get("ROOT_DOMAIN", "myregistra.net")
if f"https://{_root}" not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(f"https://{_root}")
if f"https://*.{_root}" not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(f"https://*.{_root}")


# =============================================================================
# SECURITY SETTINGS (PRODUCTION)
# =============================================================================

if not DEBUG:
    # SECURE_PROXY_SSL_HEADER is critical for detecting HTTPS behind Coolify/Traefik
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Trust the X-Forwarded-Host header from Traefik
    USE_X_FORWARDED_HOST = True

    # Let the proxy (Coolify/Nginx) handle the redirect to avoid internal Docker network loops
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "False").lower() == "true"

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Allow cookies across subdomains
    _root_domain = os.environ.get("ROOT_DOMAIN", "myregistra.net")
    SESSION_COOKIE_DOMAIN = f".{_root_domain}"
    CSRF_COOKIE_DOMAIN = f".{_root_domain}"

    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # HSTS settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# =============================================================================
# R2 / S3 STORAGE CONFIGURATION
# =============================================================================

AWS_ACCESS_KEY_ID = os.environ.get("R2_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("R2_SECRET_ACCESS_KEY")
AWS_S3_ENDPOINT_URL = os.environ.get("R2_ENDPOINT")
AWS_STORAGE_BUCKET_NAME = os.environ.get("R2_BUCKET_NAME")
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_REGION_NAME = "auto"

# Only configure S3 storage if credentials are provided
if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_S3_ENDPOINT_URL:
    # Use custom domain if provided, otherwise fallback to endpoint URL
    # Useful if R2 bucket has a public URL enabled
    _custom_domain = os.environ.get("R2_PUBLIC_URL")
    AWS_S3_CUSTOM_DOMAIN = os.environ.get("R2_CUSTOM_DOMAIN")

    # Always use signed URLs for R2 to ensure accessibility even if bucket is private
    # signatures can last up to 7 days (604800 seconds)
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 604800

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "access_key": AWS_ACCESS_KEY_ID,
                "secret_key": AWS_SECRET_ACCESS_KEY,
                "endpoint_url": AWS_S3_ENDPOINT_URL,
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "region_name": AWS_S3_REGION_NAME,
                "signature_version": AWS_S3_SIGNATURE_VERSION,
                "default_acl": None,
                "querystring_auth": AWS_QUERYSTRING_AUTH,
                "querystring_expire": AWS_QUERYSTRING_EXPIRE,
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
else:
    # Use local file storage if R2 not configured
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }


# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "django_debug.log",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}


# =============================================================================
# REDIS / CACHING CONFIGURATION
# =============================================================================

def _as_bool(value: str | None, default: bool = False) -> bool:
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}

# Default to None to allow fallback to LocMemCache if not provided.
REDIS_URL = os.environ.get("REDIS_URL")
USE_REDIS_CACHE = _as_bool(os.environ.get("USE_REDIS_CACHE"), default=True)

if REDIS_URL and USE_REDIS_CACHE:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }
else:
    # Fallback to local memory cache if Redis is not configured
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }

# Session settings - Use Redis/Cache for sessions in production
if not DEBUG:
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"
    # SESSION_COOKIE_DOMAIN and CSRF_COOKIE_DOMAIN already set in SECURITY SETTINGS block above


# Celery Configuration
# Handle local development without Redis
if REDIS_URL:
    CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", REDIS_URL)
    CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", REDIS_URL)
else:
    # Use memory broker for local dev without Redis
    CELERY_BROKER_URL = "memory://"
    CELERY_RESULT_BACKEND = None
    CELERY_TASK_ALWAYS_EAGER = True  # Run tasks synchronously
    CELERY_TASK_EAGER_PROPAGATES = True

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes

from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'check-subscription-expiry-daily': {
        'task': 'schools.tasks.check_subscription_expiry',
        'schedule': crontab(hour=0, minute=0),  # Run daily at midnight
    },
    'cleanup-expired-sessions-daily': {
        'task': 'core.tasks.cleanup_expired_sessions',
        'schedule': crontab(hour=3, minute=0),  # Run daily at 3 AM
    },
    'auto-report-generation-monthly': {
        'task': 'schools.tasks.auto_report_generation',
        'schedule': crontab(day_of_month=28, hour=0, minute=0), 
    },
    'monitor-pgbouncer-pools': {
        'task': 'core.tasks.monitor_pgbouncer_pools',
        'schedule': crontab(minute='*/5'),  # Every 5 minutes
    },
}



# =============================================================================
# EMAIL CONFIGURATION (BREVO / SMTP)
# =============================================================================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("SMTP_HOST", "smtp-relay.brevo.com")
EMAIL_PORT = int(os.environ.get("SMTP_PORT", 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("SMTP_USER")
EMAIL_HOST_PASSWORD = os.environ.get("SMTP_PASS")
DEFAULT_FROM_EMAIL = os.environ.get("SMTP_FROM", "noreply@myregistra.net")
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# If credentials are not set (e.g. in dev), fallback to console backend
if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    if DEBUG:
        print("WARNING: SMTP credentials not set. Emails will be printed to console.")

# =============================================================================
# CBT CONFIGURATION
# =============================================================================
CBT_MAX_VIOLATIONS = 3          # auto-submit threshold
CBT_VIOLATION_WARN = True       # show warning overlay
CBT_LOCK_ON_EXCEED = False      # lock vs auto-submit
