# Generated by Django 6.0.1 on 2026-01-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_schoolpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['domain'], name='schools_sch_domain_71993a_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['created_at'], name='schools_sch_created_382c96_idx'),
        ),
    ]
