# Generated by Django 6.0.1 on 2026-01-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_subscriptionplan_allowed_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
