# Generated by Django 6.0.1 on 2026-01-25 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_platformmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_session', models.CharField(default='2025/2026', max_length=20)),
                ('current_term', models.CharField(default='First Term', max_length=50)),
                ('school_tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('watermark_media', models.TextField(blank=True, null=True)),
                ('director_name', models.CharField(blank=True, max_length=255, null=True)),
                ('director_signature', models.TextField(blank=True, null=True)),
                ('head_of_school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('head_of_school_signature', models.TextField(blank=True, null=True)),
                ('subjects_global', models.JSONField(blank=True, default=list)),
                ('terms_list', models.JSONField(blank=True, default=list)),
                ('show_position', models.BooleanField(default=True)),
                ('show_skills', models.BooleanField(default=True)),
                ('tiled_watermark', models.BooleanField(default=False)),
                ('next_term_begins', models.DateField(blank=True, null=True)),
                ('class_teacher_label', models.CharField(default='Class Teacher', max_length=100)),
                ('head_teacher_label', models.CharField(default='Head of School', max_length=100)),
                ('report_font_family', models.CharField(default='inherit', max_length=100)),
                ('report_scale', models.IntegerField(default=100)),
                ('landing_hero_title', models.CharField(blank=True, max_length=255, null=True)),
                ('landing_hero_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('landing_features', models.TextField(blank=True, null=True)),
                ('landing_hero_image', models.TextField(blank=True, null=True)),
                ('landing_about_text', models.TextField(blank=True, null=True)),
                ('landing_gallery_images', models.JSONField(blank=True, default=list)),
                ('landing_primary_color', models.CharField(default='#1A3A5C', max_length=7)),
                ('landing_show_stats', models.BooleanField(default=True)),
                ('landing_cta_text', models.CharField(default='Start Your Journey', max_length=50)),
                ('promotion_threshold', models.IntegerField(default=50)),
                ('promotion_rules', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('show_bank_details', models.BooleanField(default=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_sort_code', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_notes', models.TextField(blank=True, null=True)),
                ('invoice_due_days', models.IntegerField(default=14)),
                ('role_permissions', models.JSONField(blank=True, default=dict)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='schools.school')),
            ],
        ),
    ]
