# Generated by Django 6.0.1 on 2026-01-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_schoolsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
