# Generated by Django 6.0.1 on 2026-01-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_schoolsettings_landing_academic_programs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='custom_domain',
            field=models.CharField(blank=True, help_text="Optional custom domain (e.g. 'portal.vineheritage.com')", max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='domain',
            field=models.CharField(blank=True, help_text="Permanent slug/subdomain (e.g. 'vine')", max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['custom_domain'], name='schools_sch_custom__c45f51_idx'),
        ),
    ]
