# Generated by Django 6.0.1 on 2026-01-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_school_custom_domain_alter_school_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=20, null=True)),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('support_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.AddField(
            model_name='schoolpayment',
            name='payment_method',
            field=models.CharField(default='paystack', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolpayment',
            name='proof_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('bank_transfer', 'Bank Transfer')], default='paystack', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_proof',
            field=models.TextField(blank=True, null=True),
        ),
    ]
