# Generated by Django 6.0.1 on 2026-01-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_platformsettings_schoolpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='paystack_public_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='paystack_secret_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
