# Generated by Django 6.0.1 on 2026-02-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_platformsettings_paystack_public_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='email_from',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='email_host',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='email_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='email_port',
            field=models.IntegerField(blank=True, default=587, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='email_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='email_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
