# Generated by Django 6.0.1 on 2026-02-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_platformsettings_email_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='paystack_public_key',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='paystack_secret_key',
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='email_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='email_from_name',
            field=models.CharField(blank=True, default='Registra', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='email_provider',
            field=models.CharField(choices=[('smtp', 'Standard SMTP'), ('brevo_api', 'Brevo API')], default='smtp', max_length=20),
        ),
    ]
