# Generated by Django 6.0.1 on 2026-02-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_remove_platformsettings_paystack_public_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='paystack_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='paystack_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
