# Generated by Django 6.0.1 on 2026-02-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_platformsettings_paystack_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Approval Pending')], default='pending', max_length=20),
        ),
    ]
