# Generated by Django 6.0.1 on 2026-02-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_add_ai_provider_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='custom_domain_enabled',
            field=models.BooleanField(default=False, help_text='Allow school to use custom domain'),
        ),
    ]
