# Generated by Django 4.2.28 on 2026-03-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_schoolpaymentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpaymentconfig',
            name='pass_processing_fee_to_parents',
            field=models.BooleanField(default=False),
        ),
    ]
