# Generated by Django 6.0.3 on 2026-10-07 07:30

from django.db import migrations, models


def move_off_online_gateways(apps, schema_editor):
    SchoolPaymentConfig = apps.get_model("schools", "SchoolPaymentConfig")
    configs = SchoolPaymentConfig.objects.all()
    configs.filter(enable_cash=False, enable_bank_transfer=False).update(enable_bank_transfer=True)
    configs.filter(default_payment_method__in=["paystack", "flutterwave"]).update(
        default_payment_method="bank_transfer"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0023_performance_indexes"),
    ]

    operations = [
        migrations.RunPython(move_off_online_gateways, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="schoolpaymentconfig",
            name="enable_flutterwave",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentconfig",
            name="enable_paystack",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentconfig",
            name="flutterwave_public_key",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentconfig",
            name="flutterwave_secret_key",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentconfig",
            name="flutterwave_webhook_secret",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentconfig",
            name="pass_processing_fee_to_parents",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentconfig",
            name="paystack_public_key",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentconfig",
            name="paystack_secret_key",
        ),
        migrations.RemoveField(
            model_name="schoolpaymentconfig",
            name="paystack_webhook_secret",
        ),
        migrations.AlterField(
            model_name="schoolpaymentconfig",
            name="default_payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("bank_transfer", "Bank Transfer")], default="bank_transfer", max_length=20
            ),
        ),
    ]
