# Generated by Django 6.0.3 on 2026-10-09 07:53

from django.db import migrations, models

# Frozen copy of schools/plans.py at the time of this migration (annual = 3 terms).
PLANS = [
    {
        "slug": "free",
        "name": "Free",
        "price": 0,
        "max_students": 30,
        "is_custom_price": False,
        "custom_domain_enabled": False,
        "description": "For very small schools getting started. Subdomain only.",
        "features": [
            "Up to 30 students",
            "Student records & attendance",
            "Report cards & broadsheet",
            "Announcements & calendar",
            "yourschool.myregistra.net subdomain",
        ],
        "allowed_modules": [
            "students",
            "teachers",
            "classes",
            "grading",
            "attendance",
            "announcements",
            "calendar",
            "broadsheet",
        ],
    },
    {
        "slug": "starter",
        "name": "Starter",
        "price": 150000,
        "max_students": 150,
        "is_custom_price": False,
        "custom_domain_enabled": True,
        "description": "Everything a growing school needs to run day to day.",
        "features": [
            "Up to 150 students",
            "Everything in Free",
            "Fees, payments & expenses",
            "Admissions, ID cards & conduct",
            "School website & messaging",
            "Custom domain",
        ],
        "allowed_modules": [
            "students",
            "teachers",
            "classes",
            "grading",
            "attendance",
            "announcements",
            "calendar",
            "broadsheet",
            "staff",
            "bursary",
            "conduct",
            "id_cards",
            "admissions",
            "messages",
            "newsletter",
            "cms",
            "data_import",
        ],
    },
    {
        "slug": "standard",
        "name": "Standard",
        "price": 320000,
        "max_students": 400,
        "is_custom_price": False,
        "custom_domain_enabled": True,
        "description": "For established schools running more operations.",
        "features": ["Up to 400 students", "Everything in Starter", "Library, inventory & transport", "Custom domain"],
        "allowed_modules": [
            "students",
            "teachers",
            "classes",
            "grading",
            "attendance",
            "announcements",
            "calendar",
            "broadsheet",
            "staff",
            "bursary",
            "conduct",
            "id_cards",
            "admissions",
            "messages",
            "newsletter",
            "cms",
            "data_import",
            "library",
            "inventory",
            "transport",
        ],
    },
    {
        "slug": "premium",
        "name": "Premium",
        "price": 520000,
        "max_students": 800,
        "is_custom_price": False,
        "custom_domain_enabled": True,
        "description": "Digital learning and insights for larger schools.",
        "features": [
            "Up to 800 students",
            "Everything in Standard",
            "CBT exams & question bank",
            "Learning centre (LMS)",
            "School analytics",
            "Custom domain",
        ],
        "allowed_modules": [
            "students",
            "teachers",
            "classes",
            "grading",
            "attendance",
            "announcements",
            "calendar",
            "broadsheet",
            "staff",
            "bursary",
            "conduct",
            "id_cards",
            "admissions",
            "messages",
            "newsletter",
            "cms",
            "data_import",
            "library",
            "inventory",
            "transport",
            "learning",
            "question_bank",
            "exams",
            "analytics",
        ],
    },
    {
        "slug": "elite",
        "name": "Elite",
        "price": 825000,
        "max_students": 1500,
        "is_custom_price": False,
        "custom_domain_enabled": True,
        "description": "The full platform for large schools.",
        "features": ["Up to 1,500 students", "Everything in Premium", "Priority support", "Custom domain"],
        "allowed_modules": [
            "students",
            "teachers",
            "classes",
            "grading",
            "attendance",
            "announcements",
            "calendar",
            "broadsheet",
            "staff",
            "bursary",
            "conduct",
            "id_cards",
            "admissions",
            "messages",
            "newsletter",
            "cms",
            "data_import",
            "library",
            "inventory",
            "transport",
            "learning",
            "question_bank",
            "exams",
            "analytics",
        ],
    },
    {
        "slug": "enterprise",
        "name": "Enterprise",
        "price": 0,
        "max_students": None,
        "is_custom_price": True,
        "custom_domain_enabled": True,
        "description": "Groups of schools and campuses above 1,500 students.",
        "features": [
            "1,500+ students",
            "Everything in Elite",
            "Multi-campus setup",
            "Dedicated onboarding & support",
            "Custom domain",
        ],
        "allowed_modules": [
            "students",
            "teachers",
            "classes",
            "grading",
            "attendance",
            "announcements",
            "calendar",
            "broadsheet",
            "staff",
            "bursary",
            "conduct",
            "id_cards",
            "admissions",
            "messages",
            "newsletter",
            "cms",
            "data_import",
            "library",
            "inventory",
            "transport",
            "learning",
            "question_bank",
            "exams",
            "analytics",
        ],
    },
]


def install_annual_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("schools", "SubscriptionPlan")

    # The old free "enterprise" pilot plan keeps its id, so existing pilot subscriptions are
    # untouched until they expire. It is renamed and hidden so the slug can be reused.
    pilot = SubscriptionPlan.objects.filter(slug="enterprise", price=0).first()
    if pilot:
        pilot.slug = "pilot-2025"
        pilot.name = "Pilot (2025/2026)"
        pilot.is_active = False
        pilot.save(update_fields=["slug", "name", "is_active"])

    # Retire the placeholder monthly plans from the old seed command.
    SubscriptionPlan.objects.filter(slug__in=["basic", "pro"]).update(is_active=False)

    for plan in PLANS:
        values = {k: v for k, v in plan.items() if k != "slug"}
        values.update(duration_days=365, is_active=True)
        SubscriptionPlan.objects.update_or_create(slug=plan["slug"], defaults=values)


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0024_remove_school_online_gateways"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_custom_price",
            field=models.BooleanField(default=False, help_text="Priced on request (e.g. Enterprise)"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_students",
            field=models.PositiveIntegerField(blank=True, help_text="Student limit; empty = unlimited", null=True),
        ),
        migrations.RunPython(install_annual_plans, migrations.RunPython.noop),
    ]
