# Generated by Django 6.0.1 on 2026-01-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_alter_attendancerecord_created_at_and_more'),
        ('bursary', '0004_alter_studentfee_student'),
        ('schools', '0012_platformsettings_paystack_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='feecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='feeitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentlineitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['school', 'created_at'], name='bursary_exp_school__2a5f50_idx'),
        ),
        migrations.AddIndex(
            model_name='feecategory',
            index=models.Index(fields=['school', 'created_at'], name='bursary_fee_school__cc6b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='feeitem',
            index=models.Index(fields=['school', 'created_at'], name='bursary_fee_school__be835f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentlineitem',
            index=models.Index(fields=['school', 'created_at'], name='bursary_pay_school__823978_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['school', 'created_at'], name='bursary_sch_school__8736b5_idx'),
        ),
    ]
