# Generated by Django 6.0.1 on 2026-02-15 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_alter_studentachievement_category_and_more'),
        ('bursary', '0005_alter_expense_created_at_and_more'),
        ('schools', '0018_supportticket_ticketresponse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fees', models.ManyToManyField(related_name='admission_packages', to='bursary.feeitem')),
                ('intake', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='academic.admissionintake')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='schools.school')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['school', 'created_at'], name='bursary_adm_school__af2ac7_idx')],
            },
        ),
    ]
