# Generated by Django 6.0.1 on 2026-02-18 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_teacher_account_name_teacher_account_number_and_more'),
        ('bursary', '0006_admissionpackage'),
        ('schools', '0018_supportticket_ticketresponse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='First day of the month (e.g. 2025-10-01)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('total_wage_bill', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_staff', models.IntegerField(default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='schools.school')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('school', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_allowances', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('breakdown', models.JSONField(default=dict)),
                ('is_paid', models.BooleanField(default=False)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='bursary.payroll')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='schools.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='academic.teacher')),
            ],
            options={
                'unique_together': {('payroll', 'staff')},
            },
        ),
        migrations.CreateModel(
            name='SalaryAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_taxable', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='schools.school')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['school', 'created_at'], name='bursary_sal_school__da25ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalaryDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_statutory', models.BooleanField(default=False, help_text='Is this required by law? (e.g. Tax/Pension)')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='schools.school')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['school', 'created_at'], name='bursary_sal_school__7219e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffSalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('structure_data', models.JSONField(blank=True, default=dict)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary_preview', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='schools.school')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='academic.teacher')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['school', 'created_at'], name='bursary_sta_school__471fd9_idx')],
            },
        ),
    ]
