# Generated by Django 4.2.28 on 2026-03-17 14:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0007_payroll_payrollentry_salaryallowance_salarydeduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecategory',
            name='allow_partial_payments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_hash',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
    ]
