# Generated by Django 4.2.28 on 2026-03-17 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0009_backfill_payment_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_hash',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
