# Generated by Django 4.2.28 on 2026-04-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0011_feediscount'),
        ('bursary', '0011_remove_expense_bursary_exp_school__2a5f50_idx_and_more'),
    ]

    operations = [
    ]
