# Generated by Django 4.2.28 on 2026-04-30 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0012_merge_20260412_1321'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollentry',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='payrollentry',
            name='payroll',
        ),
        migrations.RemoveField(
            model_name='payrollentry',
            name='school',
        ),
        migrations.RemoveField(
            model_name='payrollentry',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='salaryallowance',
            name='school',
        ),
        migrations.RemoveField(
            model_name='salarydeduction',
            name='school',
        ),
        migrations.RemoveField(
            model_name='staffsalarystructure',
            name='school',
        ),
        migrations.RemoveField(
            model_name='staffsalarystructure',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
        migrations.DeleteModel(
            name='PayrollEntry',
        ),
        migrations.DeleteModel(
            name='SalaryAllowance',
        ),
        migrations.DeleteModel(
            name='SalaryDeduction',
        ),
        migrations.DeleteModel(
            name='StaffSalaryStructure',
        ),
    ]
