# Generated by Django 6.0.3 on 2026-10-07 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bursary", "0014_alter_admissionpackage_intake"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
