# Generated by Django 4.2.28 on 2026-02-25 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_create_demo_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emailtemplate'),
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('custom_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_body', models.TextField(blank=True, help_text='Custom HTML body if not using a template', null=True)),
                ('audience_filter', models.JSONField(blank=True, default=dict, help_text="Filters applied to select recipients (e.g. {'role': 'SCHOOL_ADMIN'})")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emailtemplate')),
            ],
        ),
        migrations.AddField(
            model_name='emaillog',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='emails.emailcampaign'),
        ),
    ]
