# Generated by Django 4.2.28 on 2026-04-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0031_conductwarning_commendation_behavioranalytics'),
        ('learning', '0005_add_question_bank_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_banks', to='academic.teacher'),
        ),
    ]
