# Generated by Django 6.0.3 on 2026-10-07 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busattendance",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
