# Generated by Django 6.0.1 on 2026-01-24 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('schools', '0004_school_contact_person_school_email_school_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['school', 'date'], name='academic_at_school__263577_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['student_class', 'date'], name='academic_at_student_534deb_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['school', 'session', 'term'], name='academic_re_school__d8bd4f_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['student', 'session', 'term'], name='academic_re_student_b777dd_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'student_no'], name='academic_st_school__307c03_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'current_class'], name='academic_st_school__240d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['names'], name='academic_st_names_f45781_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.UniqueConstraint(fields=('student', 'session', 'term'), name='unique_report_per_term'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'student_no'), name='unique_student_no_per_school'),
        ),
    ]
