# Generated by Django 6.0.1 on 2026-01-24 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_attendancesession_academic_at_school__263577_idx_and_more'),
        ('schools', '0006_platformmodule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('academic', 'Academic'), ('holiday', 'Holiday'), ('exam', 'Examination'), ('meeting', 'Meeting'), ('other', 'Other')], default='academic', max_length=20)),
                ('target_audience', models.CharField(choices=[('all', 'All'), ('teachers', 'Teachers'), ('students', 'Students'), ('parents', 'Parents')], default='all', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='schools.school')),
            ],
            options={
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['school', 'start_date'], name='academic_sc_school__fe2325_idx'), models.Index(fields=['event_type'], name='academic_sc_event_t_d0d001_idx')],
            },
        ),
    ]
