# Generated by Django 6.0.1 on 2026-01-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_reportcard_affective_reportcard_attendance_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned_fees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='discounts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
