# Generated by Django 6.0.1 on 2026-01-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_teacher_staff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_modules',
            field=models.JSONField(blank=True, default=list, help_text='List of module IDs they can access'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(blank=True, help_text='Job Title (e.g. Bursar)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tasks',
            field=models.TextField(blank=True, help_text='Assigned duties', null=True),
        ),
    ]
