# Generated by Django 6.0.1 on 2026-01-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_auto_20260129_0224'),
        ('schools', '0012_platformsettings_paystack_public_key_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('timetable', 'day_of_week', 'period'), name='unique_class_period_slot'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('teacher', 'day_of_week', 'period'), name='unique_teacher_period_slot'),
        ),
    ]
