# Generated by Django 6.0.1 on 2026-01-30 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_timetableentry_unique_class_period_slot_and_more'),
        ('schools', '0012_platformsettings_paystack_public_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='schools.school')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='academic.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academic.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'teacher'], name='academic_su_school__f62f0b_idx'), models.Index(fields=['school', 'student_class'], name='academic_su_school__eef28a_idx')],
                'unique_together': {('school', 'teacher', 'student_class', 'subject', 'session')},
            },
        ),
    ]
