# Generated by Django 6.0.1 on 2026-01-30 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_subjectteacher'),
        ('schools', '0012_platformsettings_paystack_public_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='conductentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='graderange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='gradingscheme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='schoolevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='subjectscore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='subjectteacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school', 'created_at'], name='academic_cl_school__346332_idx'),
        ),
        migrations.AddIndex(
            model_name='conductentry',
            index=models.Index(fields=['school', 'created_at'], name='academic_co_school__2f8207_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingscheme',
            index=models.Index(fields=['school', 'created_at'], name='academic_gr_school__2157dd_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['school', 'created_at'], name='academic_le_school__49ea53_idx'),
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['school', 'created_at'], name='academic_pe_school__b195a1_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'created_at'], name='academic_su_school__488824_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectscore',
            index=models.Index(fields=['school', 'created_at'], name='academic_su_school__e95787_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['school', 'created_at'], name='academic_te_school__5133e6_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['school', 'created_at'], name='academic_ti_school__9b0e5c_idx'),
        ),
    ]
