# Generated by Django 6.0.1 on 2026-02-13 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_studentachievement_studenthistory_student_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentachievement',
            name='certificate_url',
        ),
        migrations.RemoveField(
            model_name='studenthistory',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='studenthistory',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='studenthistory',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='studenthistory',
            name='student_class',
        ),
        migrations.AddField(
            model_name='studentachievement',
            name='evidence_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='from_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='term',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='to_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentachievement',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentachievement',
            name='date_achieved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentachievement',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='academic.student'),
        ),
        migrations.AlterField(
            model_name='studentachievement',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studenthistory',
            name='session',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studenthistory',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='academic.student'),
        ),
    ]
