# Generated by Django 6.0.1 on 2026-02-15 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_alter_studentachievement_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='child_dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='admissionintake',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='admissionintake',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
