# Generated by Django 6.0.1 on 2026-02-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0017_alter_admission_child_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='selected_package_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
