# Generated by Django 6.0.1 on 2026-02-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0018_admission_selected_package_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='account_name',
            field=models.CharField(blank=True, help_text='Account Name as per Bank', max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='account_number',
            field=models.CharField(blank=True, help_text='Account Number', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank Name (e.g. GTBank)', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly Basic Salary', max_digits=12),
        ),
        migrations.AddField(
            model_name='teacher',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract')], default='FULL_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pfa_name',
            field=models.CharField(blank=True, help_text='Pension Fund Administrator', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pfa_number',
            field=models.CharField(blank=True, help_text='RSA Number', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax Identification Number (TIN)', max_length=50),
        ),
    ]
