# Generated by Django 6.0.1 on 2026-02-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0020_class_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
