# Generated by Django 6.0.3 on 2026-03-24 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0021_student_assigned_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenthistory',
            name='action',
        ),
        migrations.RemoveField(
            model_name='studenthistory',
            name='from_value',
        ),
        migrations.RemoveField(
            model_name='studenthistory',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='studenthistory',
            name='term',
        ),
        migrations.RemoveField(
            model_name='studenthistory',
            name='to_value',
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='event_type',
            field=models.CharField(choices=[('promotion', 'Promotion'), ('graduation', 'Graduation'), ('withdrawal', 'Withdrawal'), ('suspension', 'Suspension'), ('reactivation', 'Reactivation')], default='promotion', max_length=50),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.class'),
        ),
        migrations.AlterField(
            model_name='studenthistory',
            name='session',
            field=models.CharField(max_length=50),
        ),
    ]
