# Generated by Django 4.2.28 on 2026-04-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0023_reportcard_ai_performance_remark_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subjectscore',
            name='academic_su_school__e95787_idx',
        ),
        migrations.AddIndex(
            model_name='subjectscore',
            index=models.Index(fields=['report_card', 'subject'], name='academic_su_report__f02a96_idx'),
        ),
    ]
