# Generated by Django 4.2.28 on 2026-04-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0026_class_report_mode_and_reportcard_early_years_observations'),
        ('academic', '0026_studentgroup'),
    ]

    operations = [
    ]
