# Generated by Django 4.2.28 on 2026-04-13 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0027_merge_20260412_1321'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='ac_student_class_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='ac_student_no_idx',
        ),
        migrations.AddField(
            model_name='reportcard',
            name='verification_hash',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='signature_url',
            field=models.CharField(blank=True, help_text='URL/Path to digital signature image', max_length=512, null=True),
        ),
    ]
