# Generated by Django 4.2.28 on 2026-04-13 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0029_reportcard_ai_academic_outlook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcard',
            name='ai_academic_outlook',
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='verification_hash',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='signature_url',
            field=models.CharField(blank=True, help_text="Teacher's digital signature image URL", max_length=512, null=True),
        ),
    ]
