# Generated by Django 4.2.28 on 2026-04-13 12:32

from django.db import migrations, models
from django.db.models import Count
import uuid


def ensure_unique_reportcard_hashes(apps, schema_editor):
    """
    Backfill and deduplicate verification_hash values before adding unique=True.
    """
    ReportCard = apps.get_model("academic", "ReportCard")

    # Ensure null hashes are populated first.
    for report in ReportCard.objects.filter(verification_hash__isnull=True).only("id", "verification_hash"):
        new_hash = uuid.uuid4()
        while ReportCard.objects.filter(verification_hash=new_hash).exists():
            new_hash = uuid.uuid4()
        report.verification_hash = new_hash
        report.save(update_fields=["verification_hash"])

    # Fix duplicate non-null hashes by keeping the first record unchanged.
    duplicates = (
        ReportCard.objects.exclude(verification_hash__isnull=True)
        .values("verification_hash")
        .annotate(hash_count=Count("id"))
        .filter(hash_count__gt=1)
    )

    for dup in duplicates:
        dup_hash = dup["verification_hash"]
        reports = ReportCard.objects.filter(verification_hash=dup_hash).order_by("id")
        keep_first = True
        for report in reports:
            if keep_first:
                keep_first = False
                continue
            new_hash = uuid.uuid4()
            while ReportCard.objects.filter(verification_hash=new_hash).exists():
                new_hash = uuid.uuid4()
            report.verification_hash = new_hash
            report.save(update_fields=["verification_hash"])


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0029_reportcard_ai_academic_outlook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcard',
            name='ai_academic_outlook',
        ),
        migrations.RunPython(ensure_unique_reportcard_hashes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reportcard',
            name='verification_hash',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='signature_url',
            field=models.CharField(blank=True, help_text="Teacher's digital signature image URL", max_length=512, null=True),
        ),
    ]
