# Generated by Django 4.2.28 on 2026-04-28 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0030_remove_reportcard_ai_academic_outlook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_type', models.CharField(choices=[('late_arrival', 'Late Arrival'), ('absenteeism', 'Absenteeism'), ('uniform_violation', 'Uniform Violation'), ('academic_neglect', 'Academic Neglect'), ('disruption', 'Class Disruption'), ('dishonesty', 'Dishonesty'), ('bullying', 'Bullying'), ('damage_property', 'Damage to Property'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('serious', 'Serious'), ('severe', 'Severe')], default='minor', max_length=20)),
                ('description', models.TextField()),
                ('incident_date', models.DateField()),
                ('action_taken', models.TextField(blank=True)),
                ('parent_notified', models.BooleanField(default=False)),
                ('parent_notification_method', models.CharField(blank=True, choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone'), ('meeting', 'In-Person Meeting')], max_length=20)),
                ('parent_response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('session', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=50)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_warnings', to='academic.student')),
            ],
            options={
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='Commendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="e.g., 'Best Student Award', 'Perfect Attendance'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('leadership', 'Leadership'), ('sports', 'Sports'), ('conduct', 'Conduct'), ('creativity', 'Creativity'), ('service', 'Service'), ('other', 'Other')], default='academic', max_length=50)),
                ('points', models.IntegerField(default=5)),
                ('award_date', models.DateField(auto_now_add=True)),
                ('evidence_url', models.CharField(blank=True, max_length=512)),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('session', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=50)),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_commendations', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commendations', to='academic.student')),
            ],
            options={
                'ordering': ['-award_date'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=50)),
                ('avg_conduct_score', models.FloatField(default=0.0)),
                ('total_commendations', models.IntegerField(default=0)),
                ('total_warnings', models.IntegerField(default=0)),
                ('trait_scores', models.JSONField(blank=True, default=dict)),
                ('commendation_points', models.IntegerField(default=0)),
                ('warning_points', models.IntegerField(default=0)),
                ('overall_rating', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('needs_improvement', 'Needs Improvement'), ('poor', 'Poor')], default='average', max_length=20)),
                ('parent_meetings', models.IntegerField(default=0)),
                ('parent_complaints', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_analytics', to='academic.student')),
            ],
            options={
                'unique_together': {('student', 'session', 'term')},
            },
        ),
    ]
