# Generated by Django 4.2.28 on 2026-04-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0031_conductwarning_commendation_behavioranalytics'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='admissionintake',
                    name='school',
                ),
                migrations.DeleteModel(
                    name='Admission',
                ),
            ],
            database_operations=[],
        )
    ]
