# Generated by Django 4.2.28 on 2026-04-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0014_alter_admissionpackage_intake'),
        ('academic', '0032_remove_admissionintake_school_delete_admission'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='AdmissionIntake',
                ),
            ],
            database_operations=[],
        )
    ]
