# Generated by Django 6.0.1 on 2026-01-24 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0004_school_contact_person_school_email_school_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('target_role', models.CharField(default='SCHOOL_ADMIN', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SCHOOL_SIGNUP', 'School Signup'), ('PAYMENT_RECORDED', 'Payment Recorded'), ('ADMIN_IMPERSONATION', 'Admin Impersonation'), ('PLAN_CREATED', 'Plan Created'), ('PLAN_UPDATED', 'Plan Updated'), ('PLAN_DELETED', 'Plan Deleted'), ('SCHOOL_DELETED', 'School Deleted'), ('SCHOOL_SUSPENDED', 'School Suspended'), ('SCHOOL_ACTIVATED', 'School Activated')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='schools.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='core_global_action_c43364_idx'), models.Index(fields=['created_at'], name='core_global_created_96691e_idx')],
            },
        ),
    ]
