# Generated by Django 6.0.1 on 2026-01-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_schoolmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalactivitylog',
            name='action',
            field=models.CharField(choices=[('SCHOOL_SIGNUP', 'School Signup'), ('PAYMENT_RECORDED', 'Payment Recorded'), ('ADMIN_IMPERSONATION', 'Admin Impersonation'), ('PLAN_CREATED', 'Plan Created'), ('PLAN_UPDATED', 'Plan Updated'), ('PLAN_DELETED', 'Plan Deleted'), ('SCHOOL_DELETED', 'School Deleted'), ('SCHOOL_SUSPENDED', 'School Suspended'), ('SCHOOL_ACTIVATED', 'School Activated'), ('RECORDS_MUTATED', 'Records Mutated'), ('SECURITY_ALERT', 'Security Alert'), ('EXPORT_DATA', 'Export Data'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout')], max_length=50),
        ),
    ]
