# Generated by Django 6.0.1 on 2026-02-10 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_globalactivitylog_action'),
        ('schools', '0015_platformsettings_paystack_public_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmessage',
            name='attachment_url',
            field=models.CharField(blank=True, default='', help_text='URL to an attached file (uploaded via FileUploadView)', max_length=500),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('bursary', 'Bursary'), ('attendance', 'Attendance'), ('announcement', 'Announcement'), ('system', 'System')], default='system', max_length=20)),
                ('link', models.CharField(blank=True, default='', help_text='Deep link path e.g. /dashboard/reports', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx'), models.Index(fields=['school', 'created_at'], name='core_notifi_school__fe8b0a_idx')],
            },
        ),
    ]
