# Generated by Django 6.0.1 on 2026-02-18 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schoolmessage_attachment_url_notification'),
        ('schools', '0018_supportticket_ticketresponse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_url', models.CharField(help_text='URL to the PDF file', max_length=500)),
                ('file_name', models.CharField(default='newsletter.pdf', max_length=255)),
                ('session', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=50)),
                ('published_by', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'is_published'], name='core_newsle_school__a2112f_idx'), models.Index(fields=['session', 'term'], name='core_newsle_session_2ec5b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='SchoolAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('target', models.CharField(choices=[('all', 'Everyone'), ('class', 'Specific Class'), ('parents', 'Parents Only'), ('teachers', 'Teachers Only'), ('staff', 'Staff Only')], default='all', max_length=20)),
                ('class_id', models.CharField(blank=True, help_text="Specific class ID if target is 'class'", max_length=100, null=True)),
                ('author_role', models.CharField(blank=True, max_length=50)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_announcements', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_announcements', to='schools.school')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['school', 'is_active'], name='core_school_school__9afb8f_idx'), models.Index(fields=['target', 'class_id'], name='core_school_target_566231_idx')],
            },
        ),
    ]
