# Generated by Django 6.0.1 on 2026-02-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_newsletter_schoolannouncement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='file_url',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='file_data',
            field=models.TextField(default='', help_text='Base64 encoded PDF or URL'),
        ),
    ]
