# Generated by Django 6.0.1 on 2026-02-19 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_newsletter_file_url_to_file_data'),
        ('schools', '0020_subscriptionplan_custom_domain_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DIRECT', 'Direct Message'), ('GROUP', 'Group Chat'), ('BROADCAST', 'Broadcast')], default='DIRECT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_muted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='schoolmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='schoolmessage',
            name='core_school_school__2c22d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='schoolmessage',
            name='core_school_school__bb8bdf_idx',
        ),
        migrations.RemoveIndex(
            model_name='schoolmessage',
            name='core_school_created_27a7f4_idx',
        ),
        migrations.AddField(
            model_name='schoolmessage',
            name='is_system_generated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='schoolmessage',
            name='attachment_url',
            field=models.CharField(blank=True, default='', help_text='URL to an attached file', max_length=500),
        ),
        migrations.AddField(
            model_name='conversation',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='schools.school'),
        ),
        migrations.AddField(
            model_name='schoolmessage',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation'),
        ),
        migrations.AddIndex(
            model_name='schoolmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='core_school_convers_9d0ed0_idx'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.conversation'),
        ),
        migrations.AddField(
            model_name='conversationparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='schoolmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='schoolmessage',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='schoolmessage',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='schoolmessage',
            name='school',
        ),
        migrations.RemoveField(
            model_name='schoolmessage',
            name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together={('user', 'conversation')},
        ),
    ]
