# Generated by Django 6.0.1 on 2026-02-19 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_conversation_conversationparticipant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmessage',
            name='conversation',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolmessage',
            name='is_system_generated',
            field=models.BooleanField(default=False),
        ),
    ]
