# Generated by Django 4.2.28 on 2026-04-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_schoolmessage_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalactivitylog',
            name='action',
            field=models.CharField(choices=[('SCHOOL_SIGNUP', 'School Signup'), ('PAYMENT_RECORDED', 'Payment Recorded'), ('ADMIN_IMPERSONATION', 'Admin Impersonation'), ('PLAN_CREATED', 'Plan Created'), ('PLAN_UPDATED', 'Plan Updated'), ('PLAN_DELETED', 'Plan Deleted'), ('SCHOOL_DELETED', 'School Deleted'), ('SCHOOL_SUSPENDED', 'School Suspended'), ('SCHOOL_ACTIVATED', 'School Activated'), ('MODULE_TOGGLED', 'Module Toggled'), ('SUBSCRIPTION_UPDATED', 'Subscription Updated'), ('RECORDS_MUTATED', 'Records Mutated'), ('ACCESS_DENIED', 'Access Denied'), ('SECURITY_ALERT', 'Security Alert'), ('EXPORT_DATA', 'Export Data'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout')], max_length=50),
        ),
    ]
